### ISSUE TITLE
Release variant crashes on startup

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#24]
**Describe the bug**
The app crashes on startup. The reason is the missing Crashlytics build. 
**To Reproduce**
1. Try opening the app

**Expected behavior**
The app should open and should display the main activity. 

**Observed behavior**
The app crashes when opened. 

**Device and Android version:** 

Google pixel 3 emulator. Android 10. Stock version. Google Play services version 20.04.14

**Stack trace**

> java.lang.RuntimeException: Unable to create application com.simplecity.amp_library.ShuttleApplication: io.a.a.a.a.c.m: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by barbeau** [comment]
@BumbleFlash was looking to update the Crashlytics SDK to the latest version, but ran into https://github.com/CUTR-at-USF/MUSER/issues/25 in the process.

@BumbleFlash for now let's just remove Crashlytics entirely and see if that works.

**Comment by barbeau** [comment]
Closed by https://github.com/CUTR-at-USF/MUSER/pull/26
